// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgJoinRaffle } from "./types/burner/tx";
import { MsgFundBurner } from "./types/burner/tx";
import { MsgStartRaffle } from "./types/burner/tx";


export { MsgJoinRaffle, MsgFundBurner, MsgStartRaffle };

type sendMsgJoinRaffleParams = {
  value: MsgJoinRaffle,
  fee?: StdFee,
  memo?: string
};

type sendMsgFundBurnerParams = {
  value: MsgFundBurner,
  fee?: StdFee,
  memo?: string
};

type sendMsgStartRaffleParams = {
  value: MsgStartRaffle,
  fee?: StdFee,
  memo?: string
};


type msgJoinRaffleParams = {
  value: MsgJoinRaffle,
};

type msgFundBurnerParams = {
  value: MsgFundBurner,
};

type msgStartRaffleParams = {
  value: MsgStartRaffle,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgJoinRaffle({ value, fee, memo }: sendMsgJoinRaffleParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgJoinRaffle: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgJoinRaffle({ value: MsgJoinRaffle.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgJoinRaffle: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgFundBurner({ value, fee, memo }: sendMsgFundBurnerParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgFundBurner: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgFundBurner({ value: MsgFundBurner.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgFundBurner: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgStartRaffle({ value, fee, memo }: sendMsgStartRaffleParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgStartRaffle: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgStartRaffle({ value: MsgStartRaffle.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgStartRaffle: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgJoinRaffle({ value }: msgJoinRaffleParams): EncodeObject {
			try {
				return { typeUrl: "/bze.burner.v1.MsgJoinRaffle", value: MsgJoinRaffle.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgJoinRaffle: Could not create message: ' + e.message)
			}
		},
		
		msgFundBurner({ value }: msgFundBurnerParams): EncodeObject {
			try {
				return { typeUrl: "/bze.burner.v1.MsgFundBurner", value: MsgFundBurner.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgFundBurner: Could not create message: ' + e.message)
			}
		},
		
		msgStartRaffle({ value }: msgStartRaffleParams): EncodeObject {
			try {
				return { typeUrl: "/bze.burner.v1.MsgStartRaffle", value: MsgStartRaffle.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgStartRaffle: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseUrl: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]>;

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });
		this.tx = txClient({ signer: client.signer, addr: client.env.rpcURL, prefix: client.env.prefix ?? "cosmos" });
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			BzeBurnerV1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;