// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bze/rewards/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the rewards module's genesis state.
type GenesisState struct {
	Params                             Params                     `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	StakingRewardList                  []StakingReward            `protobuf:"bytes,2,rep,name=staking_reward_list,json=stakingRewardList,proto3" json:"staking_reward_list"`
	StakingRewardsCounter              uint64                     `protobuf:"varint,3,opt,name=staking_rewards_counter,json=stakingRewardsCounter,proto3" json:"staking_rewards_counter,omitempty"`
	TradingRewardsCounter              uint64                     `protobuf:"varint,4,opt,name=trading_rewards_counter,json=tradingRewardsCounter,proto3" json:"trading_rewards_counter,omitempty"`
	ActiveTradingRewardList            []TradingReward            `protobuf:"bytes,5,rep,name=active_trading_reward_list,json=activeTradingRewardList,proto3" json:"active_trading_reward_list"`
	PendingTradingRewardList           []TradingReward            `protobuf:"bytes,6,rep,name=pending_trading_reward_list,json=pendingTradingRewardList,proto3" json:"pending_trading_reward_list"`
	StakingRewardParticipantList       []StakingRewardParticipant `protobuf:"bytes,7,rep,name=staking_reward_participant_list,json=stakingRewardParticipantList,proto3" json:"staking_reward_participant_list"`
	PendingUnlockParticipantList       []PendingUnlockParticipant `protobuf:"bytes,8,rep,name=pending_unlock_participant_list,json=pendingUnlockParticipantList,proto3" json:"pending_unlock_participant_list"`
	TradingRewardLeaderboardList       []TradingRewardLeaderboard `protobuf:"bytes,9,rep,name=trading_reward_leaderboard_list,json=tradingRewardLeaderboardList,proto3" json:"trading_reward_leaderboard_list"`
	TradingRewardCandidateList         []TradingRewardCandidate   `protobuf:"bytes,10,rep,name=trading_reward_candidate_list,json=tradingRewardCandidateList,proto3" json:"trading_reward_candidate_list"`
	MarketIdTradingRewardIdList        []MarketIdTradingRewardId  `protobuf:"bytes,11,rep,name=market_id_trading_reward_id_list,json=marketIdTradingRewardIdList,proto3" json:"market_id_trading_reward_id_list"`
	PendingTradingRewardExpirationList []TradingRewardExpiration  `protobuf:"bytes,12,rep,name=pending_trading_reward_expiration_list,json=pendingTradingRewardExpirationList,proto3" json:"pending_trading_reward_expiration_list"`
	ActiveTradingRewardExpirationList  []TradingRewardExpiration  `protobuf:"bytes,13,rep,name=active_trading_reward_expiration_list,json=activeTradingRewardExpirationList,proto3" json:"active_trading_reward_expiration_list"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcfcc2de72dded19, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetStakingRewardList() []StakingReward {
	if m != nil {
		return m.StakingRewardList
	}
	return nil
}

func (m *GenesisState) GetStakingRewardsCounter() uint64 {
	if m != nil {
		return m.StakingRewardsCounter
	}
	return 0
}

func (m *GenesisState) GetTradingRewardsCounter() uint64 {
	if m != nil {
		return m.TradingRewardsCounter
	}
	return 0
}

func (m *GenesisState) GetActiveTradingRewardList() []TradingReward {
	if m != nil {
		return m.ActiveTradingRewardList
	}
	return nil
}

func (m *GenesisState) GetPendingTradingRewardList() []TradingReward {
	if m != nil {
		return m.PendingTradingRewardList
	}
	return nil
}

func (m *GenesisState) GetStakingRewardParticipantList() []StakingRewardParticipant {
	if m != nil {
		return m.StakingRewardParticipantList
	}
	return nil
}

func (m *GenesisState) GetPendingUnlockParticipantList() []PendingUnlockParticipant {
	if m != nil {
		return m.PendingUnlockParticipantList
	}
	return nil
}

func (m *GenesisState) GetTradingRewardLeaderboardList() []TradingRewardLeaderboard {
	if m != nil {
		return m.TradingRewardLeaderboardList
	}
	return nil
}

func (m *GenesisState) GetTradingRewardCandidateList() []TradingRewardCandidate {
	if m != nil {
		return m.TradingRewardCandidateList
	}
	return nil
}

func (m *GenesisState) GetMarketIdTradingRewardIdList() []MarketIdTradingRewardId {
	if m != nil {
		return m.MarketIdTradingRewardIdList
	}
	return nil
}

func (m *GenesisState) GetPendingTradingRewardExpirationList() []TradingRewardExpiration {
	if m != nil {
		return m.PendingTradingRewardExpirationList
	}
	return nil
}

func (m *GenesisState) GetActiveTradingRewardExpirationList() []TradingRewardExpiration {
	if m != nil {
		return m.ActiveTradingRewardExpirationList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "bze.rewards.v1.GenesisState")
}

func init() { proto.RegisterFile("bze/rewards/v1/genesis.proto", fileDescriptor_fcfcc2de72dded19) }

var fileDescriptor_fcfcc2de72dded19 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x1b, 0x56, 0x0a, 0xb8, 0x03, 0x89, 0xf2, 0x67, 0x55, 0xbb, 0x65, 0x65, 0x88, 0xd1,
	0x0b, 0x48, 0xb4, 0x81, 0x78, 0x80, 0x4d, 0x80, 0x26, 0x81, 0x54, 0xb5, 0x70, 0xc3, 0x4d, 0x71,
	0x12, 0x2b, 0xb3, 0xda, 0x26, 0x91, 0x7d, 0x5a, 0xc6, 0x6e, 0x10, 0x6f, 0xc0, 0x23, 0xf0, 0x38,
	0xbb, 0xdc, 0x25, 0x57, 0x08, 0xb5, 0x2f, 0x82, 0x6a, 0x3b, 0xed, 0xec, 0x3a, 0x15, 0xe2, 0xae,
	0xf5, 0x77, 0xbe, 0xef, 0x77, 0x8e, 0x63, 0x1b, 0x6d, 0x07, 0xe7, 0xc4, 0x67, 0xe4, 0x0b, 0x66,
	0x11, 0xf7, 0x27, 0x07, 0x7e, 0x4c, 0x12, 0xc2, 0x29, 0xf7, 0x32, 0x96, 0x42, 0x5a, 0xbb, 0x13,
	0x9c, 0x13, 0x4f, 0xa9, 0xde, 0xe4, 0xa0, 0x71, 0x3f, 0x4e, 0xe3, 0x54, 0x48, 0xfe, 0xfc, 0x97,
	0xac, 0x6a, 0x34, 0x8d, 0x8c, 0x0c, 0x33, 0x3c, 0x52, 0x11, 0x8d, 0xc7, 0x86, 0xc8, 0x01, 0x0f,
	0x68, 0x12, 0xf7, 0xe5, 0x52, 0x41, 0x11, 0x30, 0x1c, 0xad, 0x14, 0xf9, 0x6b, 0x93, 0xfa, 0x19,
	0x66, 0x40, 0x43, 0x9a, 0xe1, 0x04, 0xa4, 0x61, 0xef, 0x27, 0x42, 0x9b, 0x6f, 0xe5, 0x3c, 0x3d,
	0xc0, 0x40, 0x6a, 0x2f, 0x51, 0x45, 0xf6, 0x56, 0x77, 0x5a, 0x4e, 0xbb, 0x7a, 0xf8, 0xd0, 0xd3,
	0xe7, 0xf3, 0x3a, 0x42, 0x3d, 0x2a, 0x5f, 0xfc, 0xde, 0x2d, 0x75, 0x55, 0x6d, 0xad, 0x87, 0xee,
	0x19, 0xa8, 0x21, 0xe5, 0x50, 0xbf, 0xd6, 0xda, 0x68, 0x57, 0x0f, 0x77, 0xcc, 0x88, 0x9e, 0x2c,
	0xed, 0x8a, 0x15, 0x95, 0x74, 0x97, 0x5f, 0x5d, 0x7c, 0x47, 0x39, 0xd4, 0x5e, 0xa1, 0x2d, 0x3d,
	0x94, 0xf7, 0xc3, 0x74, 0x9c, 0x00, 0x61, 0xf5, 0x8d, 0x96, 0xd3, 0x2e, 0x77, 0x1f, 0x68, 0x1e,
	0x7e, 0x2c, 0xc5, 0xb9, 0x4f, 0xdf, 0x9c, 0xa5, 0xaf, 0x2c, 0x7d, 0x4a, 0x36, 0x7c, 0x9f, 0x51,
	0x03, 0x87, 0x40, 0x27, 0xa4, 0xaf, 0xdb, 0xe5, 0x2c, 0xd7, 0xed, 0xb3, 0x7c, 0xb8, 0x1a, 0xa5,
	0x66, 0xd9, 0x92, 0x31, 0x9a, 0x24, 0x26, 0x0a, 0x50, 0x33, 0x23, 0x89, 0x88, 0xb6, 0x21, 0x2a,
	0xff, 0x8e, 0xa8, 0xab, 0x9c, 0x55, 0xc6, 0x18, 0xed, 0x16, 0x7f, 0x75, 0xc9, 0xb9, 0x21, 0x38,
	0xed, 0xb5, 0x9f, 0xa5, 0xb3, 0x34, 0x29, 0xe4, 0x36, 0x2f, 0xd0, 0x73, 0x6c, 0x3e, 0xda, 0x38,
	0x19, 0xa6, 0xe1, 0x60, 0x15, 0x7b, 0xd3, 0x8e, 0xed, 0x48, 0xdb, 0x47, 0xe1, 0xb2, 0x60, 0xb3,
	0x02, 0x3d, 0xc7, 0x9a, 0x3b, 0x49, 0x70, 0x44, 0x58, 0x90, 0x2e, 0x76, 0xf5, 0x96, 0x1d, 0xab,
	0xef, 0xdc, 0xd2, 0x94, 0x63, 0xa1, 0x40, 0x17, 0xd8, 0x14, 0xed, 0x18, 0xd8, 0x10, 0x27, 0x11,
	0x8d, 0x30, 0x10, 0x09, 0x45, 0x02, 0xba, 0xbf, 0x16, 0x7a, 0x9c, 0x5b, 0x14, 0xb2, 0x01, 0x56,
	0x55, 0x00, 0x01, 0xb5, 0x46, 0x98, 0x0d, 0x08, 0xf4, 0x69, 0x64, 0x9e, 0x1d, 0xaa, 0x06, 0xad,
	0x0a, 0xe6, 0x53, 0x93, 0xf9, 0x5e, 0xf8, 0x4e, 0x22, 0x8d, 0x7d, 0x92, 0xcf, 0xd9, 0x1c, 0xd9,
	0x65, 0x41, 0xfd, 0xee, 0xa0, 0xfd, 0x82, 0x03, 0x4b, 0xce, 0x32, 0xca, 0x30, 0xd0, 0x34, 0x91,
	0xf0, 0x4d, 0x3b, 0x5c, 0x4b, 0x7d, 0xbd, 0xf0, 0x28, 0xf8, 0x9e, 0xed, 0x14, 0x2f, 0xab, 0x44,
	0x0f, 0xdf, 0xd0, 0x13, 0xfb, 0xad, 0x34, 0x3b, 0xb8, 0xfd, 0x3f, 0x1d, 0x3c, 0xb2, 0x5c, 0x55,
	0xbd, 0x81, 0xa3, 0x37, 0x17, 0x53, 0xd7, 0xb9, 0x9c, 0xba, 0xce, 0x9f, 0xa9, 0xeb, 0xfc, 0x98,
	0xb9, 0xa5, 0xcb, 0x99, 0x5b, 0xfa, 0x35, 0x73, 0x4b, 0x9f, 0x9e, 0xc5, 0x14, 0x4e, 0xc7, 0x81,
	0x17, 0xa6, 0xa3, 0xf9, 0xc3, 0xfb, 0x1c, 0x0f, 0xb3, 0x53, 0x0c, 0x04, 0x8b, 0x7f, 0xfe, 0xd9,
	0xe2, 0x21, 0x86, 0xaf, 0x19, 0xe1, 0x41, 0x45, 0xbc, 0xb8, 0x2f, 0xfe, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x85, 0x96, 0xb6, 0x19, 0x4f, 0x06, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActiveTradingRewardExpirationList) > 0 {
		for iNdEx := len(m.ActiveTradingRewardExpirationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActiveTradingRewardExpirationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.PendingTradingRewardExpirationList) > 0 {
		for iNdEx := len(m.PendingTradingRewardExpirationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingTradingRewardExpirationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.MarketIdTradingRewardIdList) > 0 {
		for iNdEx := len(m.MarketIdTradingRewardIdList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MarketIdTradingRewardIdList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.TradingRewardCandidateList) > 0 {
		for iNdEx := len(m.TradingRewardCandidateList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TradingRewardCandidateList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.TradingRewardLeaderboardList) > 0 {
		for iNdEx := len(m.TradingRewardLeaderboardList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TradingRewardLeaderboardList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.PendingUnlockParticipantList) > 0 {
		for iNdEx := len(m.PendingUnlockParticipantList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingUnlockParticipantList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.StakingRewardParticipantList) > 0 {
		for iNdEx := len(m.StakingRewardParticipantList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingRewardParticipantList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.PendingTradingRewardList) > 0 {
		for iNdEx := len(m.PendingTradingRewardList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingTradingRewardList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ActiveTradingRewardList) > 0 {
		for iNdEx := len(m.ActiveTradingRewardList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActiveTradingRewardList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.TradingRewardsCounter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TradingRewardsCounter))
		i--
		dAtA[i] = 0x20
	}
	if m.StakingRewardsCounter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.StakingRewardsCounter))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StakingRewardList) > 0 {
		for iNdEx := len(m.StakingRewardList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingRewardList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.StakingRewardList) > 0 {
		for _, e := range m.StakingRewardList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.StakingRewardsCounter != 0 {
		n += 1 + sovGenesis(uint64(m.StakingRewardsCounter))
	}
	if m.TradingRewardsCounter != 0 {
		n += 1 + sovGenesis(uint64(m.TradingRewardsCounter))
	}
	if len(m.ActiveTradingRewardList) > 0 {
		for _, e := range m.ActiveTradingRewardList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingTradingRewardList) > 0 {
		for _, e := range m.PendingTradingRewardList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakingRewardParticipantList) > 0 {
		for _, e := range m.StakingRewardParticipantList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingUnlockParticipantList) > 0 {
		for _, e := range m.PendingUnlockParticipantList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TradingRewardLeaderboardList) > 0 {
		for _, e := range m.TradingRewardLeaderboardList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TradingRewardCandidateList) > 0 {
		for _, e := range m.TradingRewardCandidateList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.MarketIdTradingRewardIdList) > 0 {
		for _, e := range m.MarketIdTradingRewardIdList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PendingTradingRewardExpirationList) > 0 {
		for _, e := range m.PendingTradingRewardExpirationList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ActiveTradingRewardExpirationList) > 0 {
		for _, e := range m.ActiveTradingRewardExpirationList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingRewardList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingRewardList = append(m.StakingRewardList, StakingReward{})
			if err := m.StakingRewardList[len(m.StakingRewardList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingRewardsCounter", wireType)
			}
			m.StakingRewardsCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakingRewardsCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradingRewardsCounter", wireType)
			}
			m.TradingRewardsCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TradingRewardsCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveTradingRewardList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveTradingRewardList = append(m.ActiveTradingRewardList, TradingReward{})
			if err := m.ActiveTradingRewardList[len(m.ActiveTradingRewardList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingTradingRewardList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingTradingRewardList = append(m.PendingTradingRewardList, TradingReward{})
			if err := m.PendingTradingRewardList[len(m.PendingTradingRewardList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingRewardParticipantList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingRewardParticipantList = append(m.StakingRewardParticipantList, StakingRewardParticipant{})
			if err := m.StakingRewardParticipantList[len(m.StakingRewardParticipantList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingUnlockParticipantList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingUnlockParticipantList = append(m.PendingUnlockParticipantList, PendingUnlockParticipant{})
			if err := m.PendingUnlockParticipantList[len(m.PendingUnlockParticipantList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradingRewardLeaderboardList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradingRewardLeaderboardList = append(m.TradingRewardLeaderboardList, TradingRewardLeaderboard{})
			if err := m.TradingRewardLeaderboardList[len(m.TradingRewardLeaderboardList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TradingRewardCandidateList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TradingRewardCandidateList = append(m.TradingRewardCandidateList, TradingRewardCandidate{})
			if err := m.TradingRewardCandidateList[len(m.TradingRewardCandidateList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketIdTradingRewardIdList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketIdTradingRewardIdList = append(m.MarketIdTradingRewardIdList, MarketIdTradingRewardId{})
			if err := m.MarketIdTradingRewardIdList[len(m.MarketIdTradingRewardIdList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingTradingRewardExpirationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingTradingRewardExpirationList = append(m.PendingTradingRewardExpirationList, TradingRewardExpiration{})
			if err := m.PendingTradingRewardExpirationList[len(m.PendingTradingRewardExpirationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveTradingRewardExpirationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveTradingRewardExpirationList = append(m.ActiveTradingRewardExpirationList, TradingRewardExpiration{})
			if err := m.ActiveTradingRewardExpirationList[len(m.ActiveTradingRewardExpirationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
