// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bze/rewards/v1/staking_reward_participant.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StakingRewardParticipant struct {
	Address  string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RewardId string `protobuf:"bytes,2,opt,name=reward_id,json=rewardId,proto3" json:"reward_id,omitempty"`
	Amount   string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	JoinedAt string `protobuf:"bytes,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
}

func (m *StakingRewardParticipant) Reset()         { *m = StakingRewardParticipant{} }
func (m *StakingRewardParticipant) String() string { return proto.CompactTextString(m) }
func (*StakingRewardParticipant) ProtoMessage()    {}
func (*StakingRewardParticipant) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f80bbe4f108595d, []int{0}
}
func (m *StakingRewardParticipant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakingRewardParticipant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakingRewardParticipant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakingRewardParticipant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakingRewardParticipant.Merge(m, src)
}
func (m *StakingRewardParticipant) XXX_Size() int {
	return m.Size()
}
func (m *StakingRewardParticipant) XXX_DiscardUnknown() {
	xxx_messageInfo_StakingRewardParticipant.DiscardUnknown(m)
}

var xxx_messageInfo_StakingRewardParticipant proto.InternalMessageInfo

func (m *StakingRewardParticipant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StakingRewardParticipant) GetRewardId() string {
	if m != nil {
		return m.RewardId
	}
	return ""
}

func (m *StakingRewardParticipant) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *StakingRewardParticipant) GetJoinedAt() string {
	if m != nil {
		return m.JoinedAt
	}
	return ""
}

type PendingUnlockParticipant struct {
	Index   string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Amount  string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Denom   string `protobuf:"bytes,4,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *PendingUnlockParticipant) Reset()         { *m = PendingUnlockParticipant{} }
func (m *PendingUnlockParticipant) String() string { return proto.CompactTextString(m) }
func (*PendingUnlockParticipant) ProtoMessage()    {}
func (*PendingUnlockParticipant) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f80bbe4f108595d, []int{1}
}
func (m *PendingUnlockParticipant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingUnlockParticipant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingUnlockParticipant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingUnlockParticipant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingUnlockParticipant.Merge(m, src)
}
func (m *PendingUnlockParticipant) XXX_Size() int {
	return m.Size()
}
func (m *PendingUnlockParticipant) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingUnlockParticipant.DiscardUnknown(m)
}

var xxx_messageInfo_PendingUnlockParticipant proto.InternalMessageInfo

func (m *PendingUnlockParticipant) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *PendingUnlockParticipant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PendingUnlockParticipant) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *PendingUnlockParticipant) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterType((*StakingRewardParticipant)(nil), "bze.rewards.v1.StakingRewardParticipant")
	proto.RegisterType((*PendingUnlockParticipant)(nil), "bze.rewards.v1.PendingUnlockParticipant")
}

func init() {
	proto.RegisterFile("bze/rewards/v1/staking_reward_participant.proto", fileDescriptor_4f80bbe4f108595d)
}

var fileDescriptor_4f80bbe4f108595d = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x33, 0xfd, 0xff, 0x56, 0x3b, 0x0b, 0x17, 0xa1, 0xc8, 0x80, 0x30, 0x48, 0x57, 0x2e,
	0x34, 0xa1, 0xf8, 0x04, 0xba, 0x10, 0xdc, 0x95, 0x8a, 0x1b, 0x37, 0xe1, 0x26, 0x73, 0x49, 0xc7,
	0x36, 0x33, 0x21, 0xb9, 0xad, 0xb1, 0x0f, 0xe0, 0xda, 0xc7, 0x72, 0xd9, 0xa5, 0x4b, 0x49, 0x5e,
	0x44, 0x9a, 0x89, 0x5a, 0x17, 0x2e, 0xcf, 0xb9, 0x7c, 0xdc, 0x8f, 0xc3, 0xc3, 0x78, 0x83, 0x61,
	0x81, 0x4f, 0x50, 0xa8, 0x32, 0x5c, 0x4f, 0xc2, 0x92, 0x60, 0xa1, 0x4d, 0x1a, 0xb9, 0x2a, 0xca,
	0xa1, 0x20, 0x9d, 0xe8, 0x1c, 0x0c, 0x05, 0x79, 0x61, 0xc9, 0xfa, 0x47, 0xf1, 0x06, 0x83, 0x0e,
	0x08, 0xd6, 0x93, 0xf1, 0x0b, 0xe3, 0xe2, 0xce, 0x41, 0xb3, 0xb6, 0x9d, 0xfe, 0x20, 0xbe, 0xe0,
	0x07, 0xa0, 0x54, 0x81, 0x65, 0x29, 0xd8, 0x29, 0x3b, 0x1b, 0xce, 0xbe, 0xa2, 0x7f, 0xc2, 0x87,
	0xdd, 0x0b, 0xad, 0x44, 0xaf, 0xbd, 0x1d, 0xba, 0xe2, 0x56, 0xf9, 0xc7, 0x7c, 0x00, 0x99, 0x5d,
	0x19, 0x12, 0xff, 0xda, 0x4b, 0x97, 0x76, 0xd0, 0xa3, 0xd5, 0x06, 0x55, 0x04, 0x24, 0xfe, 0x3b,
	0xc8, 0x15, 0x57, 0x34, 0xae, 0xb8, 0x98, 0xa2, 0x51, 0xda, 0xa4, 0xf7, 0x66, 0x69, 0x93, 0xc5,
	0xbe, 0xc7, 0x88, 0xf7, 0xb5, 0x51, 0x58, 0x75, 0x16, 0x2e, 0xec, 0xdb, 0xf5, 0x7e, 0xdb, 0xfd,
	0x25, 0x30, 0xe2, 0x7d, 0x85, 0xc6, 0x66, 0xdd, 0x73, 0x17, 0xae, 0x6f, 0xde, 0x6a, 0xc9, 0xb6,
	0xb5, 0x64, 0x1f, 0xb5, 0x64, 0xaf, 0x8d, 0xf4, 0xb6, 0x8d, 0xf4, 0xde, 0x1b, 0xe9, 0x3d, 0x9c,
	0xa7, 0x9a, 0xe6, 0xab, 0x38, 0x48, 0x6c, 0xb6, 0x1b, 0xfa, 0x02, 0x96, 0xf9, 0x1c, 0x08, 0xa1,
	0x4d, 0x61, 0xf5, 0x3d, 0x3c, 0x3d, 0xe7, 0x58, 0xc6, 0x83, 0x76, 0xe1, 0xcb, 0xcf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x25, 0x03, 0xcd, 0x2a, 0x94, 0x01, 0x00, 0x00,
}

func (m *StakingRewardParticipant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakingRewardParticipant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakingRewardParticipant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JoinedAt) > 0 {
		i -= len(m.JoinedAt)
		copy(dAtA[i:], m.JoinedAt)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.JoinedAt)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RewardId) > 0 {
		i -= len(m.RewardId)
		copy(dAtA[i:], m.RewardId)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.RewardId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingUnlockParticipant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingUnlockParticipant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingUnlockParticipant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintStakingRewardParticipant(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStakingRewardParticipant(dAtA []byte, offset int, v uint64) int {
	offset -= sovStakingRewardParticipant(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StakingRewardParticipant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	l = len(m.RewardId)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	l = len(m.JoinedAt)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	return n
}

func (m *PendingUnlockParticipant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovStakingRewardParticipant(uint64(l))
	}
	return n
}

func sovStakingRewardParticipant(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStakingRewardParticipant(x uint64) (n int) {
	return sovStakingRewardParticipant(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StakingRewardParticipant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakingRewardParticipant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakingRewardParticipant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakingRewardParticipant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JoinedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JoinedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakingRewardParticipant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingUnlockParticipant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStakingRewardParticipant
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingUnlockParticipant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingUnlockParticipant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStakingRewardParticipant(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStakingRewardParticipant
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStakingRewardParticipant(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStakingRewardParticipant
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStakingRewardParticipant
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStakingRewardParticipant
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStakingRewardParticipant
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStakingRewardParticipant
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStakingRewardParticipant        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStakingRewardParticipant          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStakingRewardParticipant = fmt.Errorf("proto: unexpected end of group")
)
